language: java
jdk: oraclejdk8
dist: trusty
env:
  - COVERAGE=0.25
before_install:
 - chmod +x gradlew

before_script:
 - ./gradlew test
 - ./gradlew test jacocoTestCoverageVerification

after_success:
 - ./gradlew jacocoTestReport
 - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

deploy:
  provider: script
  script: echo "WIP"
