language: java
jdk:
  - oraclejdk8
  - oraclejdk9
dist: trusty
before_install:
 - chmod +x gradlew
before_script:
 - ./gradlew test
jobs:
 include:
   - env: COVERAGE=0.5
     script: ./gradlew -p ./monolithic/ui check
   - env: COVERAGE=0.5
     script: ./gradlew -p ./monolithic/service/cart check
   - env: COVERAGE=0.5
     script: ./gradlew -p ./monolithic/service/user check
   - env: COVERAGE=0.2
     script: ./gradlew -p ./monolithic/repository/order check
   - env: COVERAGE=0.5
     script: ./gradlew -p ./monolithic/repository/cart check
   - env: COVERAGE=0.5
     script: ./gradlew -p ./monolithic/repository/product check
   - env: COVERAGE=0.2
     script: ./gradlew -p ./monolithic/repository/user check
deploy:
  provider: script
  script: echo "WIP"
