sudo: require
services:
  - docker
language: java
jdk:
- oraclejdk8
- oraclejdk9
dist: trusty

env:
  global:
    - secure: MvmvDY/e2TPsDdf/mq0vCxP5fjklthmE6Hjf1uQfS//tx9H+4byH9xJWuIbaY63MimquVaoDat+zAWcE4xpAkCOT9/JU4+GYMwW0lAJ3wOs4cdSMLGXwAXx/SWH84zecIrZChtdeNSbDyNVBmcMGX6eaN9ckgdT3D3FTt7IVE5sWLb8hYPb/6Vtd6GTt8qxLuIG6pPHBKc48AZtpmMb15QA4AGY5C4lTGJZgVbBiiAGZnTA9PMMSqRaFM6lZFLtp3MOXuRHyhi2iDR5H+GoPkRTrTSdjZvq5viqgMSI2jgH5eRAoD+AqHf+t0MxBWqElp2+f5VMX6soOYEHfM08SxBuLn/6oHpvsAQ5GZNgT4+dEVo190nmizFMNl9Ej34vuGa9twBFjnodDCAgkb0DJklh8uULwMxHwy8MocMx6AtTUwizCNgMMJrKdf1VsfSaBX26zduujzXgMxvhhJrRzrBUmWOUAvB1hW8SqR0I81mntwBt44y4mZzi0u2/wcrZlTl1ehuefE590SWm0ubEDZnH1sGIJwc19N/QcEGcL4A9EpeLJKg2koSBJShWGaLF3PUULo9rj6ZpjpSmnLBMacYMlp5Lu9e24rsUeJv3e+pMIO8vv87Wu8DMb1IMCha4VGQ/IZ+7+HxxFHERmmlgG6Rahqm/+SssSMdLLLtOWV+c=
  jobs:
  - COVERAGE=0.5 FEATURE=ui
  - COVERAGE=0.5 FEATURE=service/cart
  - COVERAGE=0.5 FEATURE=service/user
  - COVERAGE=0.2 FEATURE=repository/order
  - COVERAGE=0.5 FEATURE=repository/cart
  - COVERAGE=0.5 FEATURE=repository/product
  - COVERAGE=0.2 FEATURE=repository/user

before_install:
- chmod +x gradlew
before_script:
- "./gradlew test"

script:
- COVERAGE=$COVERAGE ./gradlew -p ./monolithic/$FEATURE check

after_script:
  - bash -c "echo \"${DOCKER_PASSWORD}\" | docker login --username \"${DOCKER_LOGIN}\" --password-stdin"

deploy:
  provider: script
  script:
    - echo "WIP"
  on:
    branch: master
    condition: $FEATURE = ui
